export const FONT_REGULAR ="Inter-Regular"
export const FONT_MEDIUM = "Inter-Medium"
export const FONT_BOLD = "Inter-Bold"
export const FONT_SEMIBOLD = "Inter-SemiBold"
export const FONT_EXTRABOLD = "Inter-ExtraBold"
